spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: false
        deregister: false
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    auto.register.schema: false
kafka:
  request-topic: workshop_camunda_request_topic
  # properties for mock
  feedback-topic: workshop_camunda_feedback_topic
  autostartup: false