spring:
  profiles:
    default: OUTGOING
  http:
    log-request-details: true
  application:
    name: CamundaSidecar
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema:
        registry:
          url: http://localhost:8081
          ssl:
            keystore:
              location: src/main/resources/mycert.jks
              password: changeit
            truststore:
              location: src/main/resources/mycert.jks
              password: changeit
            key:
              password: changeit
      spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
      specific.avro.reader: true
  mvc:
    problemdetails:
      enabled: true