spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        deregister: true
        #health-check-interval: 5s
        #health-check-path: /health/check
        #health-check-critical-timeout: 10s
        #instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        heartbeat:
          enabled: true
          ttl: 5s
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1
  kafka:
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: camunda-sidecar-local
      auto-offset-reset: earliest
camunda:
  server:
    url: http://localhost:8080/engine-rest
kafka:
  feedback-topic: workshop_camunda_feedback_topic
  autostartup: false